# Makefile ----------------------------------------------------------------

all:
	cd tb_stim; $(MAKE); cd ..
	cd tb_stim_ex/answer; $(MAKE); cd ../..
	cd tb_full_adder; $(MAKE); cd ..
	cd tb_full_adder_2; $(MAKE); cd ..
	cd tb_counter; $(MAKE); cd ..
	cd tb_add4; $(MAKE); cd ..
	cd tb_add4_fa; $(MAKE); cd ..
	cd tb_bin2therm; $(MAKE); cd ..
	cd tb_tdc_all; $(MAKE); cd ..
	cd tb_tdc_ideal; $(MAKE); cd ..
	cd tb_tdc_dline; $(MAKE); cd ..
	cd tb_dco_all; $(MAKE); cd ..
	cd tb_dco_lin; $(MAKE); cd ..
	cd tb_fdiv16; $(MAKE); cd ..
	cd tb_locking; $(MAKE); cd ..
	cd tb_phasestep; $(MAKE); cd ..
	cd tb_jtran; $(MAKE); cd ..
	cd tb_jhist; $(MAKE); cd ..

clean:
	cd tb_stim; $(MAKE) clean; cd ..
	cd tb_stim_ex; $(MAKE) clean; cd ..
	cd tb_stim_ex/answer; $(MAKE) clean; cd ../..
	cd tb_full_adder; $(MAKE) clean; cd ..
	cd tb_full_adder_2; $(MAKE) clean; cd ..
	cd tb_counter; $(MAKE) clean; cd ..
	cd tb_add4; $(MAKE) clean; cd ..
	cd tb_add4_fa; $(MAKE) clean; cd ..
	cd tb_bin2therm; $(MAKE) clean; cd ..
	cd tb_tdc_all; $(MAKE) clean; cd ..
	cd tb_tdc_ideal; $(MAKE) clean; cd ..
	cd tb_tdc_dline; $(MAKE) clean; cd ..
	cd tb_dco_all; $(MAKE) clean; cd ..
	cd tb_dco_lin; $(MAKE) clean; cd ..
	cd tb_fdiv16; $(MAKE) clean; cd ..
	cd tb_locking; $(MAKE) clean; cd ..
	cd tb_phasestep; $(MAKE) clean; cd ..
	cd tb_jtran; $(MAKE) clean; cd ..
	cd tb_jhist; $(MAKE) clean; cd ..

