# Makefile ----------------------------------------------------------------
TIMESCALE = 1ps/1ps

tb_compare:
	xmodel tb_compare.sv --top tb_compare --timescale ${TIMESCALE} \
			--simtime 100ns

clean:
	xmodel --clean

